name: Build iOS

on: [workflow_dispatch]
#   pull_request: 
#     types: ['labeled']

jobs:
  build-android:
    # if: contains(github.event.pull_request.labels.*.name, 'ios-build')
  
    name: Build iOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ios

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..

      - name: Set version
        run: agvtool new-version -all ${{ github.run_number }}

      - name: Set Keys
        run: /usr/libexec/PlistBuddy -c "Set :bugsnag:apiKey ${{ secrets.BUGSNAG_KEY }}" ./ios/RocketChatRN/Info.plist
              /usr/libexec/PlistBuddy -c "Set :bugsnag:apiKey ${{ secrets.BUGSNAG_KEY }}" ./ios/ShareRocketChatRN/Info.plist
              /usr/libexec/PlistBuddy -c "Set IS_OFFICIAL NO" ./ios/RocketChatRN/Info.plist
              /usr/libexec/PlistBuddy -c "Set IS_OFFICIAL NO" ./ios/ShareRocketChatRN/Info.plist
              /usr/libexec/PlistBuddy -c "Set IS_OFFICIAL NO" ./ios/NotificationService/Info.plist

      - name: Decode P8
        run: echo ${{ secrets.APP_STORE_CONNECT_API_BASE64 }} | base64 --decode > ./ios/fastlane/app_store_connect_api_key.p8
      
      - name: Run fastlane
        run: cd ios && fastlane ios build_experimental