name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

# on:
#   pull_request:
#     branches:
#       - develop


jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test -w 8

      - name: Codecov
        run: yarn codecov

  android-build:
    name: Android build
    runs-on: ubuntu-latest
    needs: test-and-lint
    

    env:
      JAVA_OPTS: '-Xms512m -Xmx2g'
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
      TERM: dumb

    steps:
      - name: Check out Git repository 
        uses: actions/checkout@v2
