name: Build Android

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    env:
      JAVA_OPTS: '-Xms512m -Xmx2g'
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
      TERM: dumb

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: zulu
          distribution: '11'
          cache: 'gradle'
      
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App APK
        run: |
          cd android && ./gradlew bundleExperimentalPlayDebug --no-daemon


